-- MySQL Script generated by MySQL Workbench
-- Wed Mar  7 22:56:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Info` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `mydb`.`User_Task_Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Task_Post` (
  `task_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`task_id`, `user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Task_Serve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Task_Serve` (
  `task_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `poster_id` INT NOT NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Post` (
  `post_id` INT NOT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Follow_Up`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Follow_Up` (
  `follow_up_id` INT NOT NULL,
  `user_id` INT NULL,
  `post_id` INT NULL,
  PRIMARY KEY (`follow_up_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Tag` (
  `user_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task_Info` (
  `task_id` INT NOT NULL,
  `task_poster_id` INT NULL,
  `is_taken` TINYINT NULL,
  `is_completed` TINYINT NULL,
  `task_title` VARCHAR(200) NULL,
  `task_content` VARCHAR(1000) NULL,
  `location` GEOMETRY NULL,
  `post_time` TIMESTAMP NULL,
  `taken_time` TIMESTAMP NULL,
  `completed_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task_Tag` (
  `task_id` INT NOT NULL,
  `skill_tag_id` INT NOT NULL,
  PRIMARY KEY (`task_id`, `skill_tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post_Info` (
  `post_id` INT NOT NULL,
  `posted_id` INT NULL,
  `post_time` TIMESTAMP NULL,
  `post_title` VARCHAR(200) NULL,
  `post_content` VARCHAR(1000) NULL,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post_Tag` (
  `post_id` INT NOT NULL,
  `topic_tag_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `topic_tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Follow_Up_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Follow_Up_Info` (
  `follow_up_id` INT NOT NULL,
  `post_id` INT NULL,
  `poster_id` INT NULL,
  `index` INT NULL,
  `content` VARCHAR(1000) NULL,
  `post_time` TIMESTAMP NULL,
  PRIMARY KEY (`follow_up_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skill_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skill_Tag` (
  `skill_tag_id` INT NOT NULL,
  `skill` VARCHAR(45) NULL,
  `skill_description` VARCHAR(200) NULL,
  PRIMARY KEY (`skill_tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Topic_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Topic_Tag` (
  `topic_tag_id` INT NOT NULL,
  `topic` VARCHAR(45) NULL,
  `topic_description` VARCHAR(1000) NULL,
  PRIMARY KEY (`topic_tag_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
